name = "proxy"
main = "_worker.js"
compatibility_date = "2023-08-23"

[unsafe.metadata.observability]
enabled = true

[observability.logs]
enabled = true

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.

 [env.staging.observability]
enabled = true
head_sampling_rate = 1 # optional
